
export const LOCAL_STORAGE_KEY_TOP_LEVEL_TASKS_COMPLETED = 'cryptoFlightTopLevelTasksCompleted';
export const LOCAL_STORAGE_KEY_ALL_TASK_ITEMS_COMPLETION_STATE = 'cryptoFlightAllTaskItemsCompletionState';
